apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-api-job
spec:
  schedule: "59 23 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name:  mongo-express
            image:  mongo-express
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo jon is working
          restartPolicy: OnFailure